### ISSUE TITLE
Getting "anubad" not found error with "sudo make link"

### ISSUE THREAD

**Issue by samundra** [foss-np/anubad#14] opened 2016-07-11 02:36 UTC
I tried to test the latest changes in the experimental branch with "sudo make link" as per instruction on the document but it failed with "anubad" not found error. Perhaps the link is not created as expected. 

I also tried to run application from `python3 main.py` I then ended up with another issue https://github.com/foss-np/anubad/issues/13

**Comment by rhoit** [comment] 2016-07-11 04:46
there has been small changes..

`sudo make link` not in the root directory but in `src`
check the README.

https://github.com/foss-np/anubad#12-symbolic-link

**Comment by samundra** [comment] 2016-07-11 06:53
Yes I noticed this change. I fixed the issue reported and as I said I ended up with another https://github.com/foss-np/anubad/issues/13.

**Comment by rhoit** [comment] 2016-07-11 07:23
not a bug closing it.

**Closed as completed by rhoit** 2016-07-11 07:23 UTC
Labels: invalid
